apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: {{ .Values.database.name }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: {{ .Values.database.name }}
