apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: {{ "postgres" | b64enc | quote }}
  password: {{ "password" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
type: Opaque
data:
  auth-token: {{ "app-VTb4e1e0I5FvjfDT2npvCNQc" | b64enc | quote }}
  auth-token-chart: {{ "app-STHJ8wo6RilBMhqMCbjS4rS4" | b64enc | quote }}
  superset-token: {{ "zpur3uBvOhRJZCxgiTO7+EVPEwwsxwHNapjhM97Msx9qW57qj0r0mtGB" | b64enc | quote }}
  secret-key: {{ "Y9+bBLPT9lBwY+P150VlVKTtH1XLRLbVp1NxeVVj/nOi8QN+diM54bfk" | b64enc | quote }}
