"""initial migrate

Revision ID: 598709cfe851
Revises: 
Create Date: 2025-01-03 15:03:49.803151

"""
from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision = '598709cfe851'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphmates_charts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chart_type', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('sql_query', sa.Text(), nullable=True),
    sa.Column('llm_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('dataset_relation_id', sa.String(length=36), nullable=True),
    sa.Column('is_bookmarked', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graphmates_database_connections',
    sa.Column('id', models.StringUUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('db_type', sa.String(length=20), nullable=False),
    sa.Column('db_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.String(length=10), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('connection_uri', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='graphmates_database_connections_pkey')
    )
    op.create_table('graphmates_dataset_relations',
    sa.Column('id', models.StringUUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('dataset_ids', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='graphmates_dataset_relations_pkey')
    )
    op.create_table('graphmates_upload_files',
    sa.Column('id', models.StringUUID(), nullable=False),
    sa.Column('storage_type', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name='graphmates_upload_file_pkey')
    )
    op.create_table('graphmates_dataset_desc',
    sa.Column('id', models.StringUUID(), nullable=False),
    sa.Column('file_id', models.StringUUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['graphmates_upload_files.id'], ),
    sa.PrimaryKeyConstraint('id', name='graphmates_dataset_desc_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graphmates_dataset_desc')
    op.drop_table('graphmates_upload_files')
    op.drop_table('graphmates_dataset_relations')
    op.drop_table('graphmates_database_connections')
    op.drop_table('graphmates_charts')
    # ### end Alembic commands ###
